package com.greilly.note.model;

/**
 * Created by Greg on 11/18/2016.
 */
public class Note {
    /** Autogenerated id */
    private long id;
    private String body;

    public Note(long id, String body) {
        this.id = id;
        this.body = body;
    }

    public String getBody() {
        return body;
    }
}
